services:
  app:
    image: shenol10/habit-tracker-api-app:1.0.0
    container_name: habit-tracker-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      REDIS_URL: ${REDIS_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER:-habit-tracker-api}
      JWT_EXPIRATION_DURATION: ${JWT_EXPIRATION_DURATION:-PT10M}
      REFRESH_TOKEN_EXPIRATION_DURATION: ${REFRESH_TOKEN_EXPIRATION_DURATION:-P7D}
      HABIT_RETENTION_PERIOD: ${HABIT_RETENTION_PERIOD:-P14D}
      USER_RETENTION_PERIOD: ${USER_RETENTION_PERIOD:-P14D}

  frontend:
    image: shenol10/habit-tracker-frontend:1.0.0
    container_name: habit-tracker-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - app